spring:
  datasource:
    url: jdbc:mysql://localhost:3306/podstawy?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
    continue-on-error: true
  jpa:
    generate_ddl: true
    hibernate:
      auto-dll: update